import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose              from 'mongoose';
import request               from 'supertest';
import jwt                   from 'jsonwebtoken';

jest.mock('../../../src/shared/services/email.service', () => ({
  emailService: { sendInviteEmail: jest.fn(), sendWelcomeEmail: jest.fn() },
}));
jest.mock('../../../src/shared/services/audit.service', () => ({
  auditService: { log: jest.fn().mockResolvedValue(undefined) },
}));
jest.mock('../../../src/shared/services/s3.service', () => ({
  s3Service: {
    uploadFile:      jest.fn().mockResolvedValue('mocked-s3-key'),
    getPresignedUrl: jest.fn().mockResolvedValue('https://s3.test/presigned-url'),
  },
}));
jest.mock('../../../src/modules/notification/notification.service', () => ({
  notificationService: {
    sendNotification: jest.fn().mockResolvedValue(undefined),
    sendToRole:       jest.fn().mockResolvedValue(undefined),
  },
}));

import app             from '../../../src/app';
import { TenantModel }  from '../../../src/modules/tenant/tenant.model';
import { PatientModel } from '../../../src/modules/patient/patient.model';
import { PaymentModel } from '../../../src/modules/payment/payment.model';
import { TenantStatus, UserRole } from '../../../src/shared/types/common.types';

const JWT_SECRET = process.env.JWT_SECRET!;

let mongod:   MongoMemoryServer;
let tenantId: string;
let patientId: string;

function tokenFor(role: UserRole, tid = tenantId): string {
  return jwt.sign(
    { tenantId: tid, isFirstLogin: false, userId: new mongoose.Types.ObjectId().toString(), role, email: `${role.toLowerCase()}@test.com` },
    JWT_SECRET, { expiresIn: '1h' },
  );
}

async function createTenant(name: string): Promise<string> {
  const tenant = await TenantModel.create({
    name, adminEmail: `admin@${name.replace(/\s/g, '').toLowerCase()}.com`, status: TenantStatus.ACTIVE,
    onboardingDocuments: {
      registrationCertificate: 'cert', gstNumber: 'GST', panCard: 'PAN',
      addressLine: '1 Street', city: 'Pune', state: 'Maharashtra', pincode: '411001',
    },
    branding: { displayName: name, primaryColor: '#1A73E8', logoUrl: null },
  });
  return (tenant._id as mongoose.Types.ObjectId).toString();
}

let seq = 0;
function pay(overrides: Record<string, unknown>) {
  seq += 1;
  return {
    paymentId: `pay-${String(seq).padStart(6, '0')}`, tenantId, patientId, amount: 100,
    paymentMethod: 'CASH', description: 'Consultation', status: 'COMPLETED', createdBy: 'u',
    ...overrides,
  };
}

function dataRows(csv: string): string[] {
  const lines = csv.split('\r\n');
  const start = lines.findIndex((l) => l.startsWith('S.No,')) + 1;
  return lines.slice(start, lines.indexOf('', start));
}

function summaryLine(csv: string, label: string): string[] {
  return csv.split('\r\n').find((l) => l.startsWith(`${label},`))!.split(',');
}

beforeAll(async () => {
  mongod = await MongoMemoryServer.create();
  await mongoose.connect(mongod.getUri());
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongod.stop();
});

beforeEach(async () => {
  await Promise.all(Object.values(mongoose.connection.collections).map((c) => c.deleteMany({})));
  tenantId = await createTenant('Export Test Hospital');
  const patient = await PatientModel.create({
    tenantId, fullName: 'Ravi Kumar', dateOfBirth: new Date('1990-01-01'), gender: 'MALE',
    mobileNumber: '9876543210', address: '1 Main St',
  });
  patientId = patient.patientId;
});

describe('GET /api/payments/export', () => {
  test('returns a CSV attachment with header metadata', async () => {
    const res = await request(app)
      .get('/api/payments/export?period=CUSTOM&dateFrom=2025-03-10&dateTo=2025-03-12')
      .set('Authorization', `Bearer ${tokenFor(UserRole.FINANCE_MANAGER)}`);

    expect(res.status).toBe(200);
    expect(res.headers['content-type']).toMatch(/text\/csv/);
    expect(res.headers['content-disposition']).toBe('attachment; filename="payments-custom-2025-03-10_to_2025-03-12.csv"');
    expect(res.headers['cache-control']).toBe('no-store');
    expect(res.text).toContain('Hospital,Export Test Hospital');
    expect(res.text).toContain('Report Type,Custom Range');
    expect(res.text).toContain('Timezone,"Asia/Kolkata (IST, UTC+05:30)"');
    expect(res.text).toContain('Generated By,finance_manager@test.com');
    expect(res.text).toMatch(/Generated At,\d{4}-\d{2}-\d{2} \d{2}:\d{2} IST/);
  });

  test('day boundaries are IST: 23:59 IST is included, 00:00 IST next day is not', async () => {
    await PaymentModel.create([
      pay({ amount: 1,  createdAt: new Date('2025-03-09T18:29:59.999Z') }), // 2025-03-09 23:59 IST — before
      pay({ amount: 10, createdAt: new Date('2025-03-09T18:30:00.000Z') }), // 2025-03-10 00:00 IST — in
      pay({ amount: 20, createdAt: new Date('2025-03-10T18:29:59.999Z') }), // 2025-03-10 23:59 IST — in
      pay({ amount: 40, createdAt: new Date('2025-03-10T18:30:00.000Z') }), // 2025-03-11 00:00 IST — after
    ]);

    const res = await request(app)
      .get('/api/payments/export?period=DAILY&date=2025-03-10')
      .set('Authorization', `Bearer ${tokenFor(UserRole.MANAGER)}`);

    expect(res.status).toBe(200);
    const rows = dataRows(res.text);
    expect(rows).toHaveLength(2);
    expect(rows[0]).toMatch(/^1,2025-03-10,00:00,/);
    expect(rows[1]).toMatch(/^2,2025-03-10,23:59,/);
    expect(summaryLine(res.text, 'Grand Total')).toEqual(['Grand Total', '2', '30.00']);
  });

  test('WEEKLY / MONTHLY cover the calendar week (Mon–Sun) and month', async () => {
    await PaymentModel.create([
      pay({ amount: 5,   createdAt: new Date('2025-03-02T06:00:00.000Z') }), // Sun 2 Mar — previous week
      pay({ amount: 50,  createdAt: new Date('2025-03-03T06:00:00.000Z') }), // Mon 3 Mar
      pay({ amount: 70,  createdAt: new Date('2025-03-09T06:00:00.000Z') }), // Sun 9 Mar
      pay({ amount: 900, createdAt: new Date('2025-04-01T06:00:00.000Z') }), // next month
    ]);
    const token = tokenFor(UserRole.HOSPITAL_ADMIN);

    const weekly = await request(app).get('/api/payments/export?period=WEEKLY&date=2025-03-05').set('Authorization', `Bearer ${token}`);
    expect(weekly.text).toContain('Period From,2025-03-03');
    expect(weekly.text).toContain('Period To,2025-03-09');
    expect(summaryLine(weekly.text, 'Grand Total')).toEqual(['Grand Total', '2', '120.00']);

    const monthly = await request(app).get('/api/payments/export?period=MONTHLY&date=2025-03-20').set('Authorization', `Bearer ${token}`);
    expect(monthly.text).toContain('Period To,2025-03-31');
    expect(summaryLine(monthly.text, 'Grand Total')).toEqual(['Grand Total', '3', '125.00']);
  });

  test('method breakdown reconciles with the grand total; only COMPLETED counts', async () => {
    const at = new Date('2025-03-10T06:00:00.000Z');
    await PaymentModel.create([
      pay({ amount: 100.25, paymentMethod: 'CASH',   createdAt: at }),
      pay({ amount: 200.5,  paymentMethod: 'CASH',   createdAt: at }),
      pay({ amount: 300,    paymentMethod: 'UPI',    createdAt: at }),
      pay({ amount: 0.1,    paymentMethod: 'CARD',   createdAt: at }),
      pay({ amount: 0.2,    paymentMethod: 'CARD',   createdAt: at }),
      pay({ amount: 1000,   paymentMethod: 'CHEQUE', createdAt: at }),
      pay({ amount: 999,    paymentMethod: 'UPI',    createdAt: at, status: 'PENDING' }),
      pay({ amount: 999,    paymentMethod: 'CARD',   createdAt: at, status: 'FAILED' }),
      pay({ amount: 999,    paymentMethod: 'CASH',   createdAt: at, status: 'CANCELLED' }),
      pay({ amount: 999,    paymentMethod: 'CASH',   createdAt: at, status: 'CANCELLED' }),
    ]);

    const res = await request(app)
      .get('/api/payments/export?period=DAILY&date=2025-03-10')
      .set('Authorization', `Bearer ${tokenFor(UserRole.ADMIN)}`);

    expect(res.status).toBe(200);
    expect(dataRows(res.text)).toHaveLength(6);
    expect(summaryLine(res.text, 'Cash')).toEqual(['Cash', '2', '300.75']);
    expect(summaryLine(res.text, 'UPI')).toEqual(['UPI', '1', '300.00']);
    expect(summaryLine(res.text, 'Card')).toEqual(['Card', '2', '0.30']);
    expect(summaryLine(res.text, 'Cheque')).toEqual(['Cheque', '1', '1000.00']);
    expect(summaryLine(res.text, 'Grand Total')).toEqual(['Grand Total', '6', '1601.05']);
    expect(summaryLine(res.text, 'Pending')).toEqual(['Pending', '1']);
    expect(summaryLine(res.text, 'Failed')).toEqual(['Failed', '1']);
    expect(summaryLine(res.text, 'Cancelled')).toEqual(['Cancelled', '2']);

    // Totals agree with the existing /summary endpoint for the same range.
    const summary = await request(app)
      .get('/api/payments/summary?dateFrom=2025-03-09T18:30:00.000Z&dateTo=2025-03-10T18:29:59.999Z')
      .set('Authorization', `Bearer ${tokenFor(UserRole.ADMIN)}`);
    expect(summary.body.data.total).toBeCloseTo(1601.05, 2);
  });

  test('decrypts description / transactionId and resolves patient name', async () => {
    await PaymentModel.create(pay({
      paymentMethod: 'UPI', description: 'OPD Consultation, Visit #3', transactionId: 'UTR123',
      createdAt: new Date('2025-03-10T06:00:00.000Z'),
    }));
    const res = await request(app)
      .get('/api/payments/export?period=DAILY&date=2025-03-10')
      .set('Authorization', `Bearer ${tokenFor(UserRole.ADMIN)}`);
    expect(dataRows(res.text)[0]).toBe(
      `1,2025-03-10,11:30,pay-${String(seq).padStart(6, '0')},${patientId},Ravi Kumar,"OPD Consultation, Visit #3",UPI,UTR123,100.00`,
    );
    expect(res.text).not.toContain('enc:v1:');
  });

  test('pagination: exports every row across multiple pages, including tied timestamps', async () => {
    const tie = new Date('2025-03-10T06:00:00.000Z');
    const docs = Array.from({ length: 1234 }, (_, i) => pay({
      amount: 1,
      paymentMethod: ['CASH', 'UPI', 'CARD'][i % 3],
      // ~half share one identical createdAt so page boundaries fall inside a tie
      createdAt: i % 2 === 0 ? tie : new Date(tie.getTime() + i * 1000),
    }));
    await PaymentModel.insertMany(docs);

    const res = await request(app)
      .get('/api/payments/export?period=DAILY&date=2025-03-10')
      .set('Authorization', `Bearer ${tokenFor(UserRole.FINANCE_MANAGER)}`);

    expect(res.status).toBe(200);
    const rows = dataRows(res.text);
    expect(rows).toHaveLength(1234);
    const ids = new Set(rows.map((r) => r.split(',')[3]));
    expect(ids.size).toBe(1234);
    expect(summaryLine(res.text, 'Cash')).toEqual(['Cash', '412', '412.00']);
    expect(summaryLine(res.text, 'UPI')).toEqual(['UPI', '411', '411.00']);
    expect(summaryLine(res.text, 'Card')).toEqual(['Card', '411', '411.00']);
    expect(summaryLine(res.text, 'Grand Total')).toEqual(['Grand Total', '1234', '1234.00']);
  }, 60000);

  test('never includes another tenant\'s payments', async () => {
    const otherTenant = await createTenant('Other Hospital');
    await PaymentModel.create([
      pay({ amount: 10, createdAt: new Date('2025-03-10T06:00:00.000Z') }),
      pay({ amount: 5000, tenantId: otherTenant, createdAt: new Date('2025-03-10T06:00:00.000Z') }),
    ]);
    const res = await request(app)
      .get('/api/payments/export?period=DAILY&date=2025-03-10')
      .set('Authorization', `Bearer ${tokenFor(UserRole.ADMIN)}`);
    expect(summaryLine(res.text, 'Grand Total')).toEqual(['Grand Total', '1', '10.00']);
  });

  describe('access control', () => {
    test.each([UserRole.MANAGER, UserRole.FINANCE_MANAGER, UserRole.HOSPITAL_ADMIN, UserRole.ADMIN])(
      '%s can export', async (role) => {
        const res = await request(app).get('/api/payments/export?period=DAILY&date=2025-03-10').set('Authorization', `Bearer ${tokenFor(role)}`);
        expect(res.status).toBe(200);
      },
    );

    test.each([UserRole.RECEPTIONIST, UserRole.DOCTOR, UserRole.NURSE])(
      '%s is forbidden (403)', async (role) => {
        const res = await request(app).get('/api/payments/export?period=DAILY&date=2025-03-10').set('Authorization', `Bearer ${tokenFor(role)}`);
        expect(res.status).toBe(403);
      },
    );

    test('unauthenticated is 401', async () => {
      const res = await request(app).get('/api/payments/export?period=DAILY');
      expect(res.status).toBe(401);
    });
  });

  describe('validation', () => {
    const token = () => tokenFor(UserRole.ADMIN);
    test.each([
      ['missing period',            ''],
      ['unknown period',            'period=YEARLY'],
      ['custom without dates',      'period=CUSTOM'],
      ['custom reversed',           'period=CUSTOM&dateFrom=2025-03-10&dateTo=2025-03-01'],
      ['invalid calendar date',     'period=DAILY&date=2025-02-30'],
      ['wrong format',              'period=DAILY&date=10-03-2025'],
      ['future date',               'period=DAILY&date=2999-01-01'],
      ['custom range over 366 days','period=CUSTOM&dateFrom=2023-01-01&dateTo=2025-01-01'],
    ])('%s → 400', async (_label, qs) => {
      const res = await request(app).get(`/api/payments/export?${qs}`).set('Authorization', `Bearer ${token()}`);
      expect(res.status).toBe(400);
    });
  });
});
