import { z } from 'zod';

/**
 * Validates a MongoDB ObjectId string (24-character hex).
 */
export const objectIdSchema = z
  .string()
  .regex(/^[0-9a-fA-F]{24}$/, 'Invalid ID format');

/**
 * Validates the custom Patient ID format (PAT-XXXXXXXX).
 */
export const patientIdSchema = z
  .string()
  .regex(/^PAT-[0-9A-Z]{8}$/, 'Invalid Patient ID format');

/**
 * Validates a UUID v4 string.
 */
export const uuidSchema = z.string().uuid('Invalid UUID format');

/**
 * Common schema for pagination query parameters.
 */
export const paginationSchema = z.object({
  page:  z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});

/**
 * Common schema for search query parameters.
 */
export const searchSchema = paginationSchema.extend({
  q: z.string().max(100).optional(),
});

/**
 * Rich-text fields (Notes / Progress Notes) store HTML generated by the
 * client's Tiptap editor. Strips tags/entities so callers can validate the
 * *visible* character count a user actually typed, independent of however
 * much wrapping markup formatting adds.
 */
const RICH_TEXT_TAG_REGEX = /<[^>]+>/g;
const RICH_TEXT_ENTITIES: Record<string, string> = {
  amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'", nbsp: ' ',
};

export function stripRichTextTags(html: string): string {
  return html
    .replace(RICH_TEXT_TAG_REGEX, '')
    .replace(/&(amp|lt|gt|quot|#39|nbsp);/g, (_, entity) => RICH_TEXT_ENTITIES[entity] ?? '');
}

/**
 * Server-side counterpart to the client's `sanitizeNotesHtml`
 * (client/lib/notes-html.ts). A rich-text Notes/Progress-note field reaches
 * the database through this API, so a direct request bypassing the editor
 * could otherwise store any tag/CSS it likes. This drops any tag outside the
 * editor's own set (keeping the tag's text content) and rewrites `style` to
 * only the font-family/font-size declarations the editor's toolbar can
 * actually produce — no other CSS property (position, z-index, dimensions,
 * background/url(...), etc.) can be stored and later rendered for another
 * user.
 */
const RICH_TEXT_ALLOWED_TAGS = new Set(['p', 'strong', 'em', 'u', 'ul', 'ol', 'li', 'br', 'span']);

// Must stay in sync with FONT_SIZES / FONT_FAMILIES in
// client/components/ui/rich-text-editor.tsx — the only values the editor's
// toolbar can ever produce.
const RICH_TEXT_ALLOWED_FONT_SIZES = new Set(['12px', '14px', '16px', '20px']);
const RICH_TEXT_ALLOWED_FONT_FAMILIES = new Set([
  'Arial, Helvetica, sans-serif',
  'Helvetica, Arial, sans-serif',
  '"Times New Roman", Times, serif',
  'Georgia, serif',
  'Verdana, Geneva, sans-serif',
  'Tahoma, Geneva, sans-serif',
  '"Trebuchet MS", sans-serif',
  '"Courier New", Courier, monospace',
  'monospace',
]);

function sanitizeRichTextStyleValue(style: string): string {
  return style
    .split(';')
    .map((decl) => decl.trim())
    .filter(Boolean)
    .map((decl) => {
      const idx = decl.indexOf(':');
      if (idx === -1) return null;
      const prop  = decl.slice(0, idx).trim().toLowerCase();
      const value = decl.slice(idx + 1).trim();
      if (prop === 'font-size' && RICH_TEXT_ALLOWED_FONT_SIZES.has(value)) return `font-size: ${value}`;
      if (prop === 'font-family' && RICH_TEXT_ALLOWED_FONT_FAMILIES.has(value)) return `font-family: ${value}`;
      return null;
    })
    .filter((v): v is string => v !== null)
    .join('; ');
}

function sanitizeRichTextTagAttrs(attrs: string): string {
  const styleMatch = /style\s*=\s*"([^"]*)"/i.exec(attrs);
  if (!styleMatch) return '';
  const sanitized = sanitizeRichTextStyleValue(styleMatch[1]);
  return sanitized ? ` style="${sanitized}"` : '';
}

const RICH_TEXT_TAG_OR_TEXT_REGEX = /<(\/?)([a-zA-Z]+)([^>]*)>|([^<]+)/g;

export function sanitizeRichTextHtml(html: string): string {
  let out = '';
  let m: RegExpExecArray | null;
  RICH_TEXT_TAG_OR_TEXT_REGEX.lastIndex = 0;
  while ((m = RICH_TEXT_TAG_OR_TEXT_REGEX.exec(html)) !== null) {
    const [, closing, rawName, attrs, text] = m;
    if (text !== undefined) { out += text; continue; }
    const name = rawName.toLowerCase();
    if (!RICH_TEXT_ALLOWED_TAGS.has(name)) continue; // drop tag, keep surrounding text
    out += closing ? `</${name}>` : `<${name}${sanitizeRichTextTagAttrs(attrs)}>`;
  }
  return out;
}
